# Generated by Django 5.2.8 on 2025-11-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('codigo_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nome_marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=12)),
                ('ano', models.IntegerField()),
                ('codigo_empresa', models.IntegerField()),
                ('id_departamento', models.IntegerField()),
                ('id_marca', models.IntegerField()),
                ('id_produto', models.IntegerField()),
                ('quantidade', models.CharField(max_length=50)),
                ('valor_unitario', models.CharField(max_length=50)),
                ('valor_total', models.CharField(max_length=50)),
                ('custo_unitario', models.CharField(max_length=50)),
                ('custo_total', models.CharField(max_length=50)),
                ('markup_multiplicador', models.CharField(max_length=50)),
            ],
        ),
    ]
